### ISSUE TITLE
AttributeError: 'PullRequest' object has no attribute 'draft'

### ISSUE THREAD

**Issue by yarikoptic** [con/solidation#1]
very odd on why it happened and only when it got to that feedstock

```shell
(git)smaug:/mnt/datasets/con/solidation-con[master]git
$> datalad run -m "Fetch 1st report" 'GITHUB_TOKEN=$(git config hub.oauthtoken) code/code/healthcheck.py > reports/$(date --iso-8601).txt'
[INFO   ] == Command start (output follows) ===== 
2023-02-14T12:14:39-0500 [INFO    ] solidation solidation 0.1.0
2023-02-14T12:14:39-0500 [INFO    ] solidation Processing repo con/catenate
2023-02-14T12:14:39-0500 [INFO    ] solidation Processing repo con/centerforopenneuroscience.org
2023-02-14T12:14:40-0500 [INFO    ] solidation Processing repo con/fscacher
2023-02-14T12:14:41-0500 [INFO    ] solidation Processing repo con/noisseur
2023-02-14T12:14:42-0500 [INFO    ] solidation Processing repo con/solidation
2023-02-14T12:14:43-0500 [INFO    ] solidation Processing repo con/tinuous
2023-02-14T12:14:44-0500 [INFO    ] solidation Processing repo con/tributors
2023-02-14T12:14:44-0500 [INFO    ] solidation Processing repo con/versations-archive
2023-02-14T12:14:45-0500 [INFO    ] solidation Processing repo dandi/dandi-api-webshots-tools
2023-02-14T12:14:46-0500 [INFO    ] solidation Processing repo dandi/dandi-archive
2023-02-14T12:14:52-0500 [INFO    ] solidation Processing repo dandi/dandi-cli
2023-02-14T12:14:56-0500 [INFO    ] solidation Processing repo dandi/dandi-hub
2023-02-14T12:14:58-0500 [INFO    ] solidation Processing repo dandi/dandi-schema
2023-02-14T12:15:00-0500 [INFO    ] solidation Processing repo dandi/dandisets
2023-02-14T12:15:01-0500 [INFO    ] solidation Processing repo dandi/dandisets-healthstatus
2023-02-14T12:15:02-0500 [INFO    ] solidation Processing repo dandi/example-notebooks
2023-02-14T12:15:03-0500 [INFO    ] solidation Processing repo dandi/handbook
2023-02-14T12:15:04-0500 [INFO    ] solidation Processing repo dandi/helpdesk
2023-02-14T12:15:05-0500 [INFO    ] solidation Processing repo dandi/zarr_checksum
2023-02-14T12:15:06-0500 [INFO    ] solidation Processing repo datalad/datalad
2023-02-14T12:15:15-0500 [INFO    ] solidation Processing repo datalad/datalad-container
2023-02-14T12:15:16-0500 [INFO    ] solidation Processing repo datalad/datalad-crawler
2023-02-14T12:15:17-0500 [INFO    ] solidation Processing repo datalad/datalad-deprecated
2023-02-14T12:15:18-0500 [INFO    ] solidation Processing repo datalad/datalad-fuse
2023-02-14T12:15:19-0500 [INFO    ] solidation Processing repo datalad/datalad-installer
2023-02-14T12:15:20-0500 [INFO    ] solidation Processing repo datalad/datalad-neuroimaging
2023-02-14T12:15:22-0500 [INFO    ] solidation Processing repo datalad/datalad-registry
2023-02-14T12:15:23-0500 [INFO    ] solidation Processing repo datalad/datasets.datalad.org
2023-02-14T12:15:24-0500 [INFO    ] solidation Processing repo datalad/git-annex
2023-02-14T12:15:25-0500 [INFO    ] solidation Processing repo neurodebian/dockerfiles
2023-02-14T12:15:26-0500 [INFO    ] solidation Processing repo neurodebian/neurodebian
2023-02-14T12:15:27-0500 [INFO    ] solidation Processing repo nipy/heudiconv
2023-02-14T12:15:31-0500 [INFO    ] solidation Processing repo ReproNim/containers
2023-02-14T12:15:33-0500 [INFO    ] solidation Processing repo ReproNim/reproin
2023-02-14T12:15:34-0500 [INFO    ] solidation Processing repo ReproNim/reproman
2023-02-14T12:15:37-0500 [INFO    ] solidation Processing repo ReproNim/reprostim
2023-02-14T12:15:38-0500 [INFO    ] solidation Processing repo DanielDent/git-annex-remote-rclone
2023-02-14T12:15:39-0500 [INFO    ] solidation Processing repo TheChymera/neuralynx_nwb
2023-02-14T12:15:40-0500 [INFO    ] solidation Processing repo conda-forge/annexremote-feedstock
2023-02-14T12:15:41-0500 [INFO    ] solidation Processing repo conda-forge/dandi-feedstock
2023-02-14T12:15:42-0500 [INFO    ] solidation Processing repo conda-forge/git-annex-feedstock
Traceback (most recent call last):
  File "/mnt/datasets/con/solidation-con/code/code/healthcheck.py", line 326, in <module>
    dh.render_matrix_summary()
  File "/mnt/datasets/con/solidation-con/code/code/healthcheck.py", line 231, in render_matrix_summary
    for pr in sorted((p for p in self.open_prs if not p.draft),
  File "/mnt/datasets/con/solidation-con/code/code/healthcheck.py", line 231, in <genexpr>
    for pr in sorted((p for p in self.open_prs if not p.draft),
AttributeError: 'PullRequest' object has no attribute 'draft'
```

**Comment by jwodder** [comment]
My best guess is that either (a) GitHub did not return that field for some issue for some reason, or (b) there's a bug in PyGithub, but I cannot reproduce cause (a) when querying the API directly, nor does the bug happen for me when running this script:

```python
from subprocess import CalledProcessError, check_output
from github import Github

def cmdline(*args, **kwargs):
    try:
        return check_output(args, text=True, **kwargs).strip()
    except CalledProcessError as e:
        sys.exit(e.returncode)

token = cmdline("git", "config", "hub.oauthtoken")
gh = Github(token)
repo = gh.get_repo("conda-forge/git-annex-feedstock")
for pr in repo.get_pulls(state='open'):
    print(f"{pr.number=}")
    print(f"{pr.draft=}")
    print()
```

**Comment by yarikoptic** [comment]
Thank you John for looking into it! Running your script on smaug also leads to that error.  I think the problem was even more trivial -- outdated pygithub installed globally on smaug. I now installed new one via conda - it stopped puking. Need to fight 3.11-too-moden-for-argspec issue, but that is a different story ;)
