### ISSUE TITLE
Handle issues that are converted to discussions

### ISSUE THREAD

**Issue by asmacdo** [con/solidation#41]
*Cause and to-reproduce:*

on con@smaug, running `/mnt/datasets/con/solidation-con/.git/cron-job` we get the traceback:

```
Traceback (most recent call last):
  File "/home/con/miniconda3/envs/versations/bin/solidation", line 8, in <module>
    sys.exit(main())
  File "/home/con/miniconda3/envs/versations/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/con/miniconda3/envs/versations/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/con/miniconda3/envs/versations/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/con/miniconda3/envs/versations/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/datasets/con/matrix-archive/tools/solidation/src/solidation/__main__.py", line 456, in main
    print(report.to_markdown(), end="")
  File "/mnt/datasets/con/matrix-archive/tools/solidation/src/solidation/__main__.py", line 326, in to_markdown
    for user, qty in get_by_counts(
  File "/mnt/datasets/con/matrix-archive/tools/solidation/src/solidation/__main__.py", line 417, in get_by_counts
    name = getattr(i, attr).login
AttributeError: 'NoneType' object has no attribute 'login'
```

*Investigation:*

```
ipdb> l
    416     for i in iterable:
    417         try:
    418             name = getattr(i, attr).login
    419         except Exception as e:
    420             import ipdb; ipdb.set_trace()
--> 421         counts[name] += 1
    422     return counts
    423 
    424 
    425 def ensure_aware(dt: datetime) -> datetime:
    426     # Pygithub returns naïve datetimes for timestamps with a "Z" suffix.  Until

ipdb> i
Issue(title="Dandisets "hints" and automated "tips"", number=1816)
ipdb> getattr(i, attr).login
*** AttributeError: 'NoneType' object has no attribute 'login'
ipdb> attr
'closed_by'

```

This is referencing https://github.com/dandi/dandi-archive/issues/1816, which was converted to a discussion.

I suppose that we treat this as "closed" but it isn't quite. @jwodder wdyt?

**Comment by yarikoptic** [comment]
It does say that it is closed 
![image](https://github.com/con/solidation/assets/39889/309bae79-0f4c-4d8b-8478-bb1c72971f07)
so indeed should be treated that way
